### ISSUE TITLE
Effective rainfall

### ISSUE THREAD

**Issue by akorkovelos** [akorkovelos/agrodem#1]
Equation estimating effective rainfall is not clear.

Actions needed:
- Add sources @alekordESA 
- Compare formula options and approaches that fit better @alekordESA 
- Update equations based on result @Kostas Pegios
- Review by @VividEconomics

**Comment by markwestcott34** [comment]
@markwestcott34  to review and close

**Comment by akorkovelos** [comment]
Updated equation on effective rainfall based [USDA‐SCS method](http://www.fao.org/3/x5560e/x5560e03.htm#TopOfPage), expressed through the emperical formula presented by [Barlam Panugrahi](https://books.google.se/books?id=wR9jDAAAQBAJ&pg=PA264&lpg=PA264&dq=criwar+semi+empirical+information+Pe&source=bl&ots=Bim8aJhvm3&sig=ACfU3U3xQK7FeZxIutU1-W962mydu3yesQ&hl=en&sa=X&ved=2ahUKEwjH0e3H-JriAhUxtIsKHftyB_UQ6AEwCnoECAcQAQ#v=onepage&q=criwar%20semi%20empirical%20information%20Pe&f=false
) - page 265.

**Comment by akorkovelos** [comment]
New update on calculation of effective rainfall based on [USDA‐SCS method](http://www.fao.org/3/x5560e/x5560e03.htm#TopOfPage), expressed through the emperical formula presented by [M. Ali, S. Mubarak](https://doi.org/10.9734/ARJA/2017/36812). 

Also, resolving this issue depends on issue #39
