### ISSUE TITLE
Resolution of ground water depth

### ISSUE THREAD

**Issue by akorkovelos** [akorkovelos/agrodem#11]
Depth to groundwater map currently retrieved from [here](https://www.bgs.ac.uk/research/groundwater/international/africanGroundwater/mapsDownload.html). 
Is this the resolution we want to use it with?

**Comment by akorkovelos** [comment]
New layer of water table identified from [this source](https://science.sciencemag.org/content/339/6122/940.editor-summary). The layer is available in 1km spatial resolution and is available at KTH servers as a netcdf file. At the moment no time series is available but 01-01-1970. 
Source available [here](https://science.sciencemag.org/content/339/6122/940/tab-pdf). Note that data have been acquired from personal contact with the authors.

**Comment by ngbaruah** [comment]
Another source by the BGS (but maybe more coarser than 1km): (1) https://www.bgs.ac.uk/research/groundwater/international/africanGroundwater/mapsDownload.html (2) https://iopscience.iop.org/article/10.1088/1748-9326/7/2/024009
