### ISSUE TITLE
FLAT - single or multi crop 

### ISSUE THREAD

**Issue by akorkovelos** [akorkovelos/agrodem#17]
Comparison between single and multi-crop methodology in FLAT. How does this affect the output?

**Comment by kopegios** [comment]
Pilot runs for both single crop (maize) and multi-crop (maize and cassava) for the region of Zambezia in Mozambique in 1 sq km resolution. Model ran successfully in both cases.

Quick validation attempt: compared aggregates in 10x10 vs 1x1 resolution (for maize, approximately 5000 ha difference in outputs)

**Comment by akorkovelos** [comment]
Single crop evaluation was selected due to complexity rising from processing multiple crops at the same time. Results for different crops will be combined after the irrigation model runs.
