### ISSUE TITLE
Modelling crops

### ISSUE THREAD

**Issue by akorkovelos** [akorkovelos/agrodem#19]
Decision on which crops to be modeled (staple? value?)

**Comment by markwestcott34** [comment]
Maize, Cassava, Nhemba bean (Cowpea), Small peanut

**Comment by akorkovelos** [comment]
The chosen crops are: Maize, Cassava, Dry Beans and Rice paddy. Selection was based on availavle data on harvested area at higher granularity (admin 2 level). In addition Maize and Cassava are the two most important crops in Mozambique in terms of production.
