### ISSUE TITLE
Reorganise repository

### ISSUE THREAD

**Issue by markwestcott34** [akorkovelos/agrodem#26]
(Different folders for the various elements)

**Comment by akorkovelos** [comment]
@markwestcott34 the repo has been reorganized - to a great extent. I assume there are elements for post harvesting activities and future scenarios that need to be integrated. Please review the structure - suggest modifications - add missing parts (where possible).

**Comment by markwestcott34** [comment]
Thanks Alex! Will do :)

**Comment by akorkovelos** [comment]
@markwestcott34 the repo has been reorganized once again. Please review the structure - suggest modifications - add missing parts (where possible).

**Comment by markwestcott34** [comment]
Looks great! Would suggest making clearer what is Mozambique 'test case' and what is more generic.
