### ISSUE TITLE
Is a license required for GAMS?

### ISSUE THREAD

**Issue by markwestcott34** [akorkovelos/agrodem#28]

**Comment by akorkovelos** [comment]
KTH unfortunately does not have a GAMS licence at the moment.

**Comment by markwestcott34** [comment]
@ngbaruah -- what is the best solution here, do you think? I think you thought the 'free' (?) version of GAMS would be enough but I think @kopegios is getting errors.

**Comment by ngbaruah** [comment]
Spoke to @kopegios about this last week. GAMS has two forms of limits - on solvers and on file size/optimisations - it is the latter that we are hitting the limit. The sustainable solution is re-scripting it in R/python optimisers but potential risk for hold-up. Expedient solution is using Vivid's GAMS licence - I have the licence file but will check with Onur (under whose name licence ) whether we can use it for more than 2 projects (we are currently using on 2 - VIEW and IPR). I suspect the answer will be positive but will still check and get back. If affirmative, solution is to use VE GAMS licence for now and re-work this in R/python later in the project development.

**Comment by markwestcott34** [comment]
Email FLAT authors about optimx version.

**Comment by markwestcott34** [comment]
https://neos-server.org/neos/solvers/index.html
