### ISSUE TITLE
Clean separation of inputs, code and output in repository

### ISSUE THREAD

**Issue by markwestcott34** [akorkovelos/agrodem#3]

**Comment by markwestcott34** [comment]
Would recommend data/ intermediate/ and output/ directories, with a .gitignore file so that intermediate files and outputs don't get stored on Github.

**Comment by akorkovelos** [comment]
The structure of the repository was updated so that better reflects inputs, code and output for each processing step. MD files were also added to guide any new user through processing steps. Suggest closing issue after review. @markwestcott34
