### ISSUE TITLE
Table for predictor data

### ISSUE THREAD

**Issue by markwestcott34** [akorkovelos/agrodem#32]

**Comment by akorkovelos** [comment]
Table available [here](https://docs.google.com/document/d/1iG2Aiz9jZj1-ECI6LSiWsGTwgPwww1Hvy9b45128low/edit?usp=sharing). To be discussed by the team.

**Comment by kopegios** [comment]
FLAT sample input table [here](https://github.com/alekordESA/agrodem/blob/master/GIS_RemoteSense_Processing/data_GEE_WorldClim_SoilGrids_Elev_Slope.csv)
