### ISSUE TITLE
Include soil type/content on input GIS data

### ISSUE THREAD

**Issue by akorkovelos** [akorkovelos/agrodem#39]

**Comment by akorkovelos** [comment]
Potential source [here](http://www.fao.org/soils-portal/soil-survey/soil-maps-and-databases/harmonized-world-soil-database-v12/en/). Perhaps the data hunting exercise at GEE has yielded something better? 

These data are needed to estimate the available water storage capacity in effective rainfall and the average crop water demand.

**Comment by kopegios** [comment]
**List of soil parameters (250 m)** – might add/remove some (i.e. DRAINFAO as it is a categorical variable).
 
Africa SoilGrids - Clay content - CLYPPT
Clay content (0-2 micro meter) in g/100g (w%) at 6 standard depths predicted using two sets of Africa soil profiles data.
 
Africa SoilGrids - Soil pH in H2O - PHIHOX
Soil pH x 10 in H2O at 6 standard depths (to convert to pH values divide by 10) predicted using two sets of Africa soil profiles data. Measurement units: NA.
 
Africa SoilGrids - Drainage classes – DRAINFAO
Drainage classes, defined according to the Guidelines for Soil Description (FAO, 2006) predicted using the Africa Soil Profiles Database (AfSP) v1.2. LEGEND = 1:Very poor, 2:Poor, 3:Imperfect, 4:Moderate, 5:Well, 6:Somewhat excessive, 7:Excessive, 255:NODATA.
 
Africa SoilGrids - Depth to bedrock - BDRICM
Depth to bedrock (R horizon) in cm, to maximum 175 cm, predicted using two sets of Africa soil profiles data
 
Africa SoilGrids - Bulk density (BD) - BLD
Bulk density of the soil fine earth (measured by core method) in kg / cubic-meter (kg/m3) at 6 standard depths predicted using the Africa Soil Profiles Database (AfSP) v1.2.
 
Africa SoilGrids - Texture - TEXMHT
Textural class (defined according to USDA system) at 6 depth intervals derived from sand, silt and clay contents predicted using the Africa Soil Profiles Database (AfSP) v1.2.
 
Africa SoilGrids - Soil organic carbon (SOC) - ORCDRC
Soil organic carbon content (measured by either wet oxidation or dry combustion at 900 C) in g/kg (fine earth) at 6 standard depths predicted using two sets of Africa soil profiles data.
 
Source and further details: [https://data.isric.org/geonetwork/srv/eng/catalog.search#/search?resultType=details&sortBy=relevance&fast=index&_content_type=json&from=1&to=20&any=Africa%20SoilGrids](url)
