### ISSUE TITLE
Testing repos replicability

### ISSUE THREAD

**Issue by akorkovelos** [akorkovelos/agrodem#48]
The repository shall be tested for its replicability/reproducibility; all code uploaded has been tested so far, yet an overall start-to-finish test needs to be undertakes for a small case study.

**Comment by akorkovelos** [comment]
Some ideas here might include:
- Use tags in the ipynb indicating cell functionality (input file, user input etc.)
- Use parameterization tools such as [nbparameterise](https://github.com/takluyver/nbparameterise) or [papermill](https://github.com/nteract/papermill).
- Use [nbconvert](https://nbconvert.readthedocs.io/en/latest/) to create a pdf version of the notebooks

**Comment by akorkovelos** [comment]
@oluchee any update re this?

**Comment by oluchee** [comment]
on it..would push to this branch before the end of today.
For the parameterization,  using papermill, there is a  disadvantage tho...it does not behave intuitively with inter-dependent parameters

**Comment by akorkovelos** [comment]
Updates have been tested and merged with the master branch as per commit 1e6f892f600b6236242a41ab1c960ccad6c6e69f.
