### ISSUE TITLE
cannot install pyeto on my laptop computer

### ISSUE THREAD

**Issue by Bryan-Koo** [akorkovelos/agrodem#50]
Cannot install the package, pyeto. Below is the message that I got:
![image](https://user-images.githubusercontent.com/59482144/82879815-8307bb00-9f0b-11ea-84a0-ba767ccf4899.png)

**Comment by akorkovelos** [comment]
If you clone the ```agrodem repo``` you will automatically obtain a ```pyeto``` directory that contains the python modules required to run the model. No need to install using pypi.

**Comment by Bryan-Koo** [comment]
Okay. fixed. Thanks.
