### ISSUE TITLE
Agroecological zones - Crop Calendar

### ISSUE THREAD

**Issue by akorkovelos** [akorkovelos/agrodem#6]
* Identify agroecological zones in Mozambique
* Decide on crops we are modelling in the pilot case study
* Specify crop calendar per region and crop
* Modify input files as needed to reflect the above

**Comment by ngbaruah** [comment]
http://harvestchoice.org/labs/measuring-growing-seasons

**Comment by ngbaruah** [comment]
https://www.mdpi.com/2072-4292/5/2/982
